apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment3
  template:
    metadata:
      labels:
        app: deployment3
    spec:
      containers:
      - name: my-temp-container3
        image: dockerjuggy/my-temp-image:new
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"

---

apiVersion: v1
kind: Service
metadata:
  name: service-loadbalancer
spec:
  selector:
    app: deployment3
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30003
