apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment2
  template:
    metadata:
      labels:
        app: deployment2
    spec:
      containers:
      - name: my-temp-container2
        image: dockerjuggy/my-temp-image:new
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"

---

apiVersion: v1
kind: Service
metadata:
  name: service-clusterip
spec:
  selector:
    app: deployment2
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
     # nodePort: 30002
