apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment1
  template:
    metadata:
      labels:
        app: deployment1
    spec:
      containers:
      - name: my-temp-container1
        image: dockerjuggy/my-temp-image:new
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"

---

apiVersion: v1
kind: Service
metadata:
  name: service-nodeport
spec:
  selector:
    app: deployment1
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001

